image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - module load Python
  - python -V               # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  script:
    - pip install tox flake8
    - tox -e py36,flake

run:
  script:
  - pip install . jupyter
  - jupyter nbconvert --to markdown --execute README.ipynb
  artifacts:
    paths:
    - README.md

